package com.smartliving.webapp;


import com.smartliving.webapp.dietplan.DietPlan;
import com.smartliving.webapp.dietplan.DietRepository;
import com.smartliving.webapp.exercise.*;
import com.smartliving.webapp.food.Food;
import com.smartliving.webapp.food.FoodGroup;
import com.smartliving.webapp.food.FoodRepository;
import com.smartliving.webapp.meal.Meal;
import com.smartliving.webapp.meal.MealRepository;
import com.smartliving.webapp.user.User;
import com.smartliving.webapp.user.UserRepository;
import org.hibernate.loader.plan.build.spi.ExpandingQuerySpace;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * Command line runner class to initialize database with data. Used in development.
 */
@Profile("dev")
@Configuration
public class LoadDatabase {

    private final PasswordEncoder passwordEncoder;

    @Autowired
    public LoadDatabase(PasswordEncoder passwordEncoder){
        this.passwordEncoder = passwordEncoder;
    }

    private static final Logger log = LoggerFactory.getLogger(LoadDatabase.class);

    /**
     * Preloads the food repository
     * @param
     * @return
     */
    @Bean
    CommandLineRunner initDatabase(FoodRepository foodRepository, MealRepository mealRepository,
                                   DietRepository dietRepository, UserRepository userRepository,
                                   ExerciseRepository exerciseRepository, ExercisePlanRepository exercisePlanRepository){
        // Sample Diet

        // Breakfast Foods
        Food almondMilk = new Food("Almond Milk", 30,1,3,1, FoodGroup.DAIRY);
        Food honeyNutCheerios = new Food("Honey Nut Cheerios", 140, 30, 2,3,FoodGroup.GRAIN);

        // Lunch Foods
        Food apple = new Food("Apple", 40, 10, 0,0, FoodGroup.FRUIT);
        Food whiteBread = new Food("White Bread", 90, 19,0,3, FoodGroup.GRAIN);
        Food ham = new Food("Ham", 50, 1,2,8, FoodGroup.MEAT);
        Food cheese = new Food("Cheese", 120, 10,1,6,FoodGroup.DAIRY);
        Food mayo = new Food("Mayo", 90,0,10,0, FoodGroup.FATS_OILS);


        List<Food> foods = Arrays.asList(almondMilk,honeyNutCheerios,apple,whiteBread,ham,cheese,mayo);
        foodRepository.saveAll(foods);

        Meal breakfast = new Meal("Breakfast");
        breakfast.addFood(almondMilk);
        breakfast.addFood(honeyNutCheerios);

        Meal lunch = new Meal("Lunch");
        lunch.addFood(whiteBread);
        lunch.addFood(ham);
        lunch.addFood(cheese);
        lunch.addFood(mayo);
        lunch.addFood(apple);

        DietPlan smartDiet = new DietPlan("Smart Diet");
        smartDiet.addMeal(breakfast);
        smartDiet.addMeal(lunch);


        User user = new User("jordan","jordan@gmail.com",passwordEncoder.encode("password"));
        user.addDietPlan(smartDiet);
        userRepository.save(user);

        User user1 = new User("j","jordan12@gmail.com",passwordEncoder.encode("j"));
        userRepository.save(user1);

        //Exercises name, muscleGroup, equipment
        Exercise bicepCurl = new Exercise("Bicep Curl", "Bicep", "Dumbbells");
        Exercise backSquat = new Exercise("Back Squat", "Lower Body", "Barbell");
        Exercise deadlift = new Exercise("Conventional Deadlift", "Lower Body", "Barbell");
        Exercise benchPress = new Exercise("Bench Press", "Chest", "Barbell");
        Exercise reverseChestFly = new Exercise("Reverse Chest Fly", "Back", "Dumbbells");
        Exercise barbellJammers = new Exercise("Barbell Jammers", "Abs", "Barbell");
        Exercise abCrunchMachine = new Exercise("Ab Crunch Machine", "Abs", "Machine");
        Exercise backExtensionMachine = new Exercise("Back Extension Machine", "Back", "Machine");
        Exercise bandBackFlyes = new Exercise("Band Back Flyes", "Back", "Bands");
        Exercise bandWeightedSitUp = new Exercise("Band Weighted Sit Up", "Abs", "Bands");
        Exercise bandsSeatedShoulderPress = new Exercise("Bands Seated Shoulder Press", "Shoulders", "Bands");
        Exercise barbellMilitaryPress = new Exercise("Barbell Military Press", "Shoulders", "Barbell");
        Exercise barbellBentArmPullover = new Exercise("Barbell Bent Arm Pullover", "Back", "Barbell");
        Exercise barbellBodyRow = new Exercise("Barbell Body Row", "Biceps", "Barbell");
        Exercise barbellBradfordRockyPress = new Exercise("Barbell Bradford Rocky Press", "Shoulders", "Barbell");
        Exercise barbellCloseGripBenchPress = new Exercise("Barbell Close Grip Bench Press", "Triceps", "Barbell");
        Exercise barbellCloseGripPreacherCurl = new Exercise("Barbell Close Grip Preacher Curl", "Biceps", "EZ Curl Bar");
        Exercise barbellCloseGripPressBehindNeck = new Exercise("Barbell Close Grip Press Behind the Neck", "Triceps", "Barbell");
        Exercise barbellCloseGripSeatedConcentrationCurl = new Exercise("Barbell Close Grip Seated Concentration Curl", "Biceps", "Barbell");
        Exercise barbellCurlsLyingAgainstIncline = new Exercise("Barbell Curls Lying Against An Incline", "Biceps", "Barbell");
        Exercise barbellDeclineBenchLunge = new Exercise("Barbell Decline Bench Lunge", "Upper Legs", "Barbell");
        Exercise barbellDeclineBenchPress = new Exercise("Barbell Decline Bench Press", "Chest", "Barbell");
        Exercise barbellDeclinePullover = new Exercise("Barbell Decline Pullover", "Chest", "Barbell");
        Exercise barbellFrontRaiseAndPullover = new Exercise("Barbell Front Raise and Pullover", "Chest", "Barbell");
        Exercise barbellGoodMorningOffPins = new Exercise("Barbell Good Morning Off Pins", "Upper Legs", "Barbell");
        Exercise barbellHighInvertedRow = new Exercise("Barbell High Inverted Row", "Back", "Barbell");
        Exercise barbellHipThrust = new Exercise("Barbell Hip Thrust", "Glutes", "Barbell");
        Exercise barbellInclineBenchPress = new Exercise("Barbell Incline Bench Press", "Chest", "Barbell");
        Exercise barbellInclineBenchPull = new Exercise("Barbell Incline Bench Pull", "Back", "Barbell");
        Exercise barbellInclineBenchRow = new Exercise("Barbell Incline Bench Row", "Back", "Barbell");
        Exercise barbellJMPress = new Exercise("Barbell JM Press", "Triceps", "Barbell");
        Exercise barbellLyingBackOfTheHeadExtension = new Exercise("Barbell Lying Back of the Head Tricep Extension", "Triceps", "Barbell");
        Exercise barbellLyingCamberedRow = new Exercise("Barbell Lying Cambered Row", "Back", "Barbell");
        Exercise barbellLyingCloseGripTricepsPressToChin = new Exercise("Barbell Lying Close Grip Triceps Press To Chin", "Triceps", "Barbell");
        Exercise benchDip = new Exercise("Bench Dip", "Triceps", "Bench");
        Exercise benchPressMachine = new Exercise("Bench Press Machine", "Chest", "Machine");
        Exercise benchPushup = new Exercise("Bench Pushup", "Chest", "Bench");
        Exercise biceptCurlMachine = new Exercise("Bicep Curl Machine", "Biceps", "Machine");
        Exercise butterfly = new Exercise("Butterfly", "Chest", "Machine");
        Exercise cableBackInclinePushdown = new Exercise("Cable Back Incline Pushdown", "Back", "Machine");
        Exercise cableBentOverLowPulleyLateral = new Exercise("Cable Bent Over Low Pulley Lateral", "Shoulders", "Machine");
        Exercise cableCalfRaise = new Exercise("Cable Calf Raise", "Lower Legs", "Machine");
        Exercise cableCloseGripCurl = new Exercise("Cable Close Grip Curl", "Biceps", "Machine");
        Exercise cableConcentrationCurl = new Exercise("Cable Concentration Curl", "Biceps", "Machine");
        Exercise cableCrossOver = new Exercise("Cable Cross Over", "Chest", "Machine");
        Exercise cableCrunch = new Exercise("Cable Crunch", "Abs", "Machine");
        Exercise cableDeadlift = new Exercise("Cable Deadlift", "Back", "Machine");
        Exercise cableDeclineChestFly = new Exercise("Cable Decline Chest Fly", "Back", "Machine");
        Exercise cableDeclinePress = new Exercise("Cable Decline Press", "Chest", "Machine");
        Exercise cableDeclinePullover = new Exercise("Cable Decline Pullover", "Shoulders", "Machine");
        Exercise cableDragCurl = new Exercise("Cable Drag Curl", "Biceps", "Machine");
        Exercise cableElevatedRows = new Exercise("Cable Elevated Rows", "Back", "Machine");
        Exercise cableExternalRotation = new Exercise("Cable External Rotation", "Shoulders", "Machine");
        Exercise cableFlatBenchFly = new Exercise("Cable Flat Bench Fly", "Chest", "Machine");
        Exercise cableFrontRaise = new Exercise("Cable Front Raise", "Shoulders", "Machine");
        Exercise dip = new Exercise("Dip", " Triceps", "Machine");
        Exercise dragonFlag = new Exercise("Dragon Flag", "Abs", "Bench");
        Exercise dumbbellSeatedFrontHammerRaises = new Exercise("Dumbbell Seated Front Hammer Raises", "Shoulders", "Dumbbell");
        Exercise dumbbellAlternateBentOverKickback = new Exercise("Dumbbell Alternate Bent Over Kickback", "Triceps", "Dumbbell");
        Exercise dumbbellAlternateBentOverReverseFly = new Exercise("Dumbbell Alternate Bent Over Reverse Fly", "Shoulders", "Dumbbell");
        Exercise dumbbellAlternateBicepCurl = new Exercise("Dumbbell Alternate Bicep Curl", "Biceps", "Dumbbell");
        Exercise dumbbellAlternateHammerCurl = new Exercise("Dumbbell Alternate Hammer Curl", "Biceps", "Dumbbell");
        Exercise dumbbellAlternateHammerPreacherCurl = new Exercise("Dumbbell Alternate Hammer Preacher Curl", "Biceps", "Dumbbell");
        Exercise dumbbellAlternateInclineCurl = new Exercise("Dumbbell Alternate Incline Curl", "Biceps", "Dumbbell");
        Exercise dumbbellAlternatingDeltoidRaise = new Exercise("Dumbbell Alternating Deltoid Raise", "Shoulders", "Dumbbell");
        Exercise dumbbellArnoldPress = new Exercise("Dumbbell Arnold Press", "Shoulders", "Dumbbell");
        Exercise dumbbellDeadlift = new Exercise("Dumbbell Deadlift", "Back", "Dumbbell");
        Exercise dumbbellDeclineFly = new Exercise("Dumbbell Decline Fly", "Chest", "Dumbbell");
        Exercise dumbbellDeclinePress = new Exercise("Dumbell Decline Press", "Chest", "Dumbbell");
        Exercise dumbbellDeclineTricepsExtension= new Exercise("Dumbbell Decline Triceps Extension", "Triceps", "Dumbbell");
        Exercise dumbbellDoubleInclineShoulderRaise= new Exercise("Dumbbell Double Incline Shoulder Raise", "Shoulders", "Dumbbell");
        Exercise dumbbellFly = new Exercise("Dumbbell Fly", "Chest", "Dumbbell");
        Exercise dumbbellFrontInclineRaise = new Exercise("Dumbbell Front Incline Raise", "Shoulders", "Dumbbell");
        Exercise dumbbellInclineCurl = new Exercise("Dumbbell Incline Curl", "Biceps", "Dumbbell");
        Exercise dumbbellInclineFly = new Exercise("Dumbbell Incline Fly", "Chest", "Dumbbell");
        Exercise dumbbellLateralRaise = new Exercise("Dumbbell Lateral Raise", "Shoulders", "Dumbbell");
        Exercise dumbbellLunges = new Exercise("Dumbbell Lunges", "Upper Legs", "Dumbbell");
        Exercise ezBarDeclineCloseGripSkullCrusher = new Exercise("EZ Bar Decline Close Grip Skull Crusher", "Triceps", "EZ Curl Bar");
        Exercise ezBarDeclineTricepsExtension = new Exercise("EZ Bar Decline Triceps Extension", "Triceps", "EZ Curl Bar");
        Exercise ezBarFrenchPressOnExerciseBall = new Exercise("EZ Bar French Press on Exercise Ball", "Triceps", "EZ Curl Bar");
        Exercise ezBarInclineTricepsExtension = new Exercise("EZ Bar Incline Triceps Extension", "Triceps", "EZ Curl Bar");
        Exercise ezBarLyingCloseGripBehindTheHeadTricepsExtension = new Exercise("EZ Bar Lying Close Grip Behind the Head Triceps Extension", "Triceps", "EZ Curl Bar");
        Exercise ezBarReverseGripPreacherCurl = new Exercise("EZ Bar Reverse Grip Preacher Curl", "Forearm", "EZ Curl Bar");
        Exercise ezBarSeatedCloseGripConcentrationCurl = new Exercise("EZ Bar Seated Close Grip Concentration Curl", "Biceps", "EZ Curl Bar");
        Exercise ezBarSeatedReverseGripFrenchPress = new Exercise("EZ Bar Seated Reverse Grip French Press", "Triceps", "EZ Curl Bar");
        Exercise ezBarTricepsExtension = new Exercise("EZ Bar Triceps Extension", "Triceps", "EZ Curl Bar");
        Exercise flatBenchLegPullIn = new Exercise("Flat Bench Leg Pull In", "Abs", "Bench");
        Exercise flatBenchLyingLegRaise = new Exercise("Flat Bench Lying Leg Raise", "Abs", "Bench");
        Exercise frontStepUp = new Exercise("Front Step Up", "Back", "Bench");
        Exercise fullRangeOfMotionLatPulldown = new Exercise("Full Range Of Motion Lat Pulldown", "Back", "Bench");
        Exercise girondaSternumChinUps = new Exercise("Gironda Sternum Chin Ups", "Back", "Pullup Bar");
        Exercise gorillaChinUpWithCrunch = new Exercise("Gorilla Chin Up with Crunch", "Back", "Pullup Bar");
        Exercise hackCalfRaise = new Exercise("Hack Calf Raise", "Lower Legs", "Machine");
        Exercise hackSquat = new Exercise("Hack Squat", "Lower Legs", "Machine");
        Exercise hammerGripPullUp = new Exercise("Hammer Grip Pull Up", "Back", "Pullup Bar");
        Exercise hangingKneeRaise = new Exercise("Hanging Knee Raise", "Abs", "Pullup Bar");
        Exercise hangingLegRaise = new Exercise("Hanging Leg Raise", "Abs", "Pullup Bar");
        Exercise hangingPike = new Exercise("Hanging Pike", "Abs", "Pullup Bar");
        Exercise hipAdduction = new Exercise("Hip Adduction", "Glutes", "Machine");
        Exercise hyperextensionsBackExtensions = new Exercise("Hyperextensions - Back Extensions", "Back", "Machine");
        Exercise isoLateralWidePulldown = new Exercise("Iso Lateral Wide Pulldown", "Back", "Machine");
        Exercise jackknifeSitUpOnBench = new Exercise("Jackknife Sit-Up On Bench", "Abs", "Bench");
        Exercise kneelingLegCurl = new Exercise("Kneeling Leg Curl", "Upper Legs", "Machine");
        Exercise legExtensionWithOneLeg = new Exercise("Leg Extension with One Leg", "Upper Legs", "Machine");
        Exercise legExtensions = new Exercise("Leg Extensions", "Upper Legs", "Machine");
        Exercise legPress = new Exercise("Leg Press", "Upper Legs", "Machine");
        Exercise legPressMachine = new Exercise("Leg Press Machine", "Upper Legs", "Machine");
        Exercise legPressWithWideStance = new Exercise("Leg Press with Wide Stance", "Upper Legs", "Machine");
        Exercise leverageChestPress = new Exercise("Leverage Chest Press", "Chest", "Machine");
        Exercise leverageDeclineChestPress = new Exercise("Leverage Decline Chest Press", "Chest", "Machine");
        Exercise leverageInclineChestPress = new Exercise("Leverage Incline Chest Press", "Chest", "Machine");
        Exercise leverageMachineHighRow = new Exercise("Leverage Machine High Row", "Back", "Machine");
        Exercise leverageMachineIsoRow = new Exercise("Leverage Machine Iso Row", "Back", "Machine");
        Exercise leverageShoulderPress = new Exercise("Leverage Shoulder Press", "Shoulders", "Machine");
        Exercise leverageShrug = new Exercise("Leverage Shrug", "Shoulders", "Machine");
        Exercise lyingCableCrunch = new Exercise("Lying Cable Crunch", "Abs", "Machine");
        Exercise lyingCableKneeRaiseOnBench = new Exercise("Lying Cable Knee Raise on Bench", "Abs", "Machine");
        Exercise lyingLegCurls = new Exercise("Lying Leg Curls", "Upper Legs", "Machine");
        Exercise lyingLegRaiseWithHipThrustOnBench = new Exercise("Lying Leg Raise with Hip Thrust on Bench", "Abs", "Bench");
        Exercise lyingMachineSquat = new Exercise("Lying Machine Squat", "Upper Legs", "Machine");
        Exercise machineAssistedChinUp = new Exercise("Machine Assisted Chin Up", "Back", "Machine");
        Exercise machineAssistedDip = new Exercise("Machine Assisted Dip", "Triceps", "Machine");
        Exercise machineAssistedHammerGripPullUp = new Exercise("Machine Assisted Hammer Grip Pull Up", "Back", "Machine");
        Exercise machineAssistedPullUp = new Exercise("Machine Assisted Pull Up", "Back", "Machine");
        Exercise machineCurlWithHammerGrip = new Exercise("Machine Curl With Hammer Grip", "Biceps", "Machine");
        Exercise machineCurlWithReverseGrip = new Exercise("Machine Curl With Reverse Grip", "Biceps", "Machine");
        Exercise machineDeclineChestPress = new Exercise("Machine Decline Chest Press", "Chest", "Machine");
        Exercise machineDeltoidRaise = new Exercise("Machine Deltoid Raise", "Shoulders", "Machine");
        Exercise machineInclineChestPress = new Exercise("Machine Incline Chest Press", "Chest", "Machine");
        Exercise machineInnerChestPress = new Exercise("Machine Inner Chest Press", "Chest", "Machine");
        Exercise machineLatPullDown = new Exercise("Machine Lat Pull Down", "Back", "Machine");
        Exercise machineReverseFlyes = new Exercise("Machine Reverse Flyes", "Shoulders", "Machine");
        Exercise machineShoulderPress = new Exercise("Machine Shoulder Press", "Shoulders", "Machine");
        Exercise machineTBarReverseGripRow = new Exercise("Machine T-Bar Reverse Grip Row", "Back", "Machine");
        Exercise machineTricepsExtension = new Exercise("Machine Triceps Extension", "Triceps", "Machine");
        Exercise medicineBallBicepsCurlonExerciseBall= new Exercise("Medicine Ball Biceps Curl on Exercise Ball", "Biceps", "Exercise Ball");
        Exercise mixedGripChinUp = new Exercise("Mixed Grip Chin Up", "Back", "Pullup Bar");
        Exercise narrowGripLatPullDown = new Exercise("Narrow Grip Lat Pull Down", "Back", "Machine");
        Exercise neckPress = new Exercise("Neck Press", "Chest", "Barbell");
        Exercise obliqueCrunchesWithBench = new Exercise("Oblique Crunches with Bench", "Abs", "Bench");
        Exercise obliqueRaisesOnParallelBars = new Exercise("Oblique Raises on Parallel Bars", "Abs", "Machine");
        Exercise onYourBackQuadStretch = new Exercise("On Your Back Quad Stretch", "Upper Legs", "Bench");
        Exercise oneArmChinUp = new Exercise("One Arm Chin Up", "Back", "Pullup Bar");
        Exercise oneArmIsoLateralHighRow = new Exercise("One Arm Iso Lateral High Row", "Back", "Machine");
        Exercise oneArmIsoLateralWidePulldown = new Exercise("One Arm Iso Lateral Wide Pulldown", "Back", "Machine");
        Exercise oneArmedBiasedPushUp = new Exercise("One Armed Biased Push Up", "Chest", "Exercise Ball");
        Exercise oneHandedHang = new Exercise("One Handed Hang", "Back", "Pullup Bar");
        Exercise oneLeg45DegreeLegPress = new Exercise("One Leg 45 Degree Leg Press", "Glutes", "Machine");
        Exercise oneLegCalfPressOnLegPress = new Exercise("One Leg Calf Press on Leg Press", "Lower Legs", "Machine");
        Exercise oneLegDonkeyCalfRaise = new Exercise("One Leg Donkey Calf Raise", "Lower Legs", "Bench");
        Exercise oneLegHackSquat = new Exercise("One Leg Hack Squat", "Upper Legs", "Machine");
        Exercise oneLegReverseHyperonFlatBench = new Exercise("One Leg Reverse Hyper on Flat Bench", "Abs", "Bench");
        Exercise parallelBarLegRaise = new Exercise("Parallel Bar Leg Raise", "Abs", "Machine");
        Exercise pinPresses = new Exercise("Pin Presses", "Triceps", "Barbell");
        Exercise plankOnExerciseBall = new Exercise("Plank on Exercise Ball", "Abs", "Exercise Ball");
        Exercise plankWithFeetOnBench = new Exercise("Plank with Feet on Bench", "Abs", "Bench");
        Exercise preacherCurlMachine = new Exercise("Preacher Curl Machine", "Biceps", "Machine");
        Exercise pullUps = new Exercise("Pull Ups", "Back", "Pullup Bar");
        Exercise pushUpwithFeetElevated = new Exercise("Push Up with Feet Elevated", "Chest", "Bench");
        Exercise pushUpwithFeetOnAnExerciseBall = new Exercise("Push Up with Feet On An Exercise Ball", "Chest", "Exercise Ball");
        Exercise reverseGripLatPullDown = new Exercise("Reverse Grip Lat Pull Down", "Back", "Machine");
        Exercise reverseGripMachineLatPullDown = new Exercise("Reverse Grip Machine Lat Pull Down", "Back", "Machine");
        Exercise reverseGripVerticalRow = new Exercise("Reverse Grip Vertical Row", "Back", "Machine");
        Exercise reverseHackSquat = new Exercise("Reverse Hack Squat", "Upper Legs", "Machine");
        Exercise reverseHyperonFlatBench = new Exercise("Reverse Hyper on Flat Bench", "Glutes", "Bench");
        Exercise reverseLyingTBarMachineRow = new Exercise("Reverse Lying T Bar Machine Row", "Back", "Machine");
        Exercise rockyPullUpsandPulldowns = new Exercise("Rocky Pull Ups and Pulldowns", "Back", "Pullup Bar");
        Exercise rollOveronExerciseBall = new Exercise("Roll Over on Exercise Ball", "Abs", "Exercise Ball");
        Exercise romanChairTwistingKneeRaise = new Exercise("Roman Chair Twisting Knee Raise", "Abs", "Machine");
        Exercise seatedCalfRaise = new Exercise("Seated Calf Raise", "Lower Legs", "Machine");
        Exercise seatedFlatBenchLegPullIn = new Exercise("Seated Flat Bench Leg Pull In", "Abs", "Bench");
        Exercise seatedHamstringStretchonExerciseBall = new Exercise("Seated Hamstring Stretch on Exercise Ball", "Abs", "Exercise Ball");
        Exercise seatedLegCurl = new Exercise("Seated Leg Curl", "Upper Legs", "Machine");
        Exercise seatedLegCurlwithOneLeg = new Exercise("Seated Leg Curl with One Leg", "Upper Legs", "Machine");
        Exercise seatedLegTucks = new Exercise("Seated Leg Tucks", "Abs", "Bench");
        Exercise seatedMachineRow = new Exercise("Seated Machine Row", "Back", "Machine");
        Exercise seatedOneLegCalfRaise = new Exercise("Seated One Leg Calf Raise", "Lower Legs", "Machine");
        Exercise seatedTricepDip = new Exercise("Seated Tricep Dip", "Triceps", "Machine");
        Exercise seatedTwoArmPalmsUpLowPulleyWristCurl = new Exercise("Seated Two Arm Palms Up Low Pulley Wrist Curl", "Forearm", "Machine");
        Exercise shoulderRaise = new Exercise("Shoulder Raise", "Shoulders", "Dumbbell");
        Exercise shoulderRaiseMachine = new Exercise("Shoulder Raise Machine", "Shoulders", "Machine");
        Exercise sideStepUp = new Exercise("Side Step Up", "Upper Legs", "Bench");
        Exercise singleBenchDip = new Exercise("Single Bench Dip", "Triceps", "Bench");
        Exercise singleLegCurl = new Exercise("Single Leg Curl", "Upper Legs", "Machine");
        Exercise smithMachineBenchPress = new Exercise("Smith Machine Bench Press", "Chest", "Machine");
        Exercise smithMachineBentOverRow = new Exercise("Smith Machine Bent Over Row", "Back", "Machine");


        Exercise smithMachineBicepCurl = new Exercise("Smith Machine Bicep Curl", "Biceps", "Machine");
        Exercise smithMachineCloseGripBenchPress = new Exercise("Smith Machine Close Grip Bench Press", "Triceps", "Machine");
        Exercise smithMachineCloseGripShoulderPress = new Exercise("Smith Machine Close Grip Shoulder Press", "Shoulders", "Machine");
        Exercise smithMachineDeadlift = new Exercise("Smith Machine Deadlift", "Back", "Machine");
        Exercise smithMachineDeclineBenchPress = new Exercise("Smith Machine Decline Bench Press", "Chest", "Machine");
        Exercise smithMachineDeclineCloseGripBenchPress = new Exercise("Smith Machine Decline Close Grip Bench Press", "Chest", "Machine");
        Exercise smithMachineFrankensteinSquat = new Exercise("Smith Machine Frankenstein Squat", "Upper Legs", "Machine");
        Exercise smithMachineFrontSquat = new Exercise("Smith Machine Front Squat", "Upper Legs", "Machine");
        Exercise smithMachineGoodMorning = new Exercise("Smith Machine Good Morning", "Back", "Machine");
        Exercise smithMachineHackSquat = new Exercise("Smith Machine Hack Squat", "Upper Legs", "Machine");
        Exercise smithMachineInclineBenchPress = new Exercise("Smith Machine Incline Bench Press", "Chest", "Machine");
        Exercise smithMachineInclineShoulderRaise = new Exercise("Smith Machine Incline Shoulder Raise", "Shoulders", "Machine");
        Exercise smithMachineInclineTricepExtension = new Exercise("Smith Machine Incline Tricep Extension", "Triceps", "Machine");
        Exercise smithMachineLunge = new Exercise("Smith Machine Lunge", "Glutes", "Machine");
        Exercise smithMachineOneArmRow = new Exercise("Smith Machine One Arm Row", "Back", "Machine");
        Exercise smithMachineOneLegCalfRaise = new Exercise("Smith Machine One Leg Calf Raise", "Lower Legs", "Machine");
        Exercise smithMachineOverheadShoulderPress = new Exercise("Smith Machine Overhead Shoulder Press", "Shoulders", "Machine");
        Exercise smithMachineRearDeltRow = new Exercise("Smith Machine Rear Delt Row", "Shoulders", "Machine");
        Exercise smithMachineReverseCalfRaises = new Exercise("Smith Machine Reverse Calf Raises", "Lower Legs", "Machine");
        Exercise smithMachineReverseCloseGripBenchPress = new Exercise("Smith Machine Reverse Close Grip Bench Press", "Triceps", "Machine");
        Exercise smithMachineReverseGripBenchPress = new Exercise("Smith Machine Reverse Grip Bench Press", "Chest", "Machine");
        Exercise smithMachineReverseGripBentOverRow = new Exercise("Smith Machine Reverse Grip Bent Over Row", "Back", "Machine");
        Exercise smithMachineReverseGripInclineBenchPress = new Exercise("Smith Machine Reverse Grip Incline Bench Press", "Chest", "Machine");
        Exercise smithMachineSeatedOneLegCalfRaise = new Exercise("Smith Machine Seated One Leg Calf Raise", "Lower Legs", "Machine");
        Exercise smithMachineSeatedWristCurl = new Exercise("Smith Machine Seated Wrist Curl", "Forearm", "Machine");
        Exercise smithMachineShoulderPress = new Exercise("Smith Machine Shoulder Press", "Sholders", "Machine");
        Exercise smithMachineShoulderPressBehindtheNeck = new Exercise("Smith Machine Shoulder Press Behind the Neck", "Shoulder", "Machine");
        Exercise smithMachineShrug = new Exercise("Smith Machine Shrug", "Shoulders", "Machine");
        Exercise smithMachineSingleLegSplitSquat = new Exercise("Smith Machine Single Leg Split Squat", "Upper Legs", "Machine");


        Exercise smithMachineSquat = new Exercise("Smith Machine Squat", "Upper Legs", "Machine");
        Exercise smithMachineSquattoBench = new Exercise("Smith Machine Squat to Bench", "Upper Legs", "Machine");
        Exercise smithMachineStandingBehindtheBackWristCurl = new Exercise("Smith Machine Standing Behind the Back Wrist Curl", "Forearm", "Machine");
        Exercise smithMachineStiffLeggedDeadlift = new Exercise("Smith Machine Stiff Legged Deadlift", "Upper Legs", "Machine");
        Exercise smithMachineToeRaise = new Exercise("Smith Machine Toe Raise", "Lower Legs", "Machine");
        Exercise smithMachineUprightRow = new Exercise("Smith Machine Upright Row", "Shoulders", "Machine");
        Exercise smithMachineWideGripBenchPress = new Exercise("Smith Machine Wide Grip Bench Press", "Chest", "Machine");
        Exercise smithMachineWideGripDeclineBenchPress = new Exercise("Smith Machine Wide Grip Decline Bench Press", "Chest", "Machine");
        Exercise smithMachineWideGripShoulderPress = new Exercise("Smith Machine Wide Grip Shoulder Press", "Shoulders", "Machine");
        Exercise smithMachineZercherSquat = new Exercise("Smith Machine Zercher Squat", "Upper Legs", "Machine");
        Exercise spinalStretch = new Exercise("Spinal Stretch", "Back", "Exercise Ball");
        Exercise standingCalfRaises = new Exercise("Standing Calf Raises", "Lower Legs", "Machine");
        Exercise standingElevatedQuadStretch = new Exercise("Standing Elevated Quad Stretch", "Upper Legs", "Bench");
        Exercise standingGastrocnemiusCalfStretch = new Exercise("Standing Gastrocnemius Calf Stretch", "Lower Legs", "Bench");
        Exercise standingStraightLegHamstringContractRelaxonExerciseBall= new Exercise("Standing Straight Leg Hamstring Contract Relax on Exercise Ball", "Upper Legs", "Exercise Ball");
        Exercise storkStancewithExerciseBall = new Exercise("Stork Stance with Exercise Ball", "Abs", "Exercise Ball");
        Exercise supineAbCrunchMachine = new Exercise("Supine Ab Crunch Machine", "Abs", "Machine");
        Exercise supineStraightLegHamstringStretchonExerciseBall = new Exercise("Supine Straight Leg Hamstring Stretch on Exercise Ball", "Abs", "Exercise Ball");
        Exercise tBarLyingRow = new Exercise("T Bar Lying Row", "Back", "Machine");
        Exercise tBarRow = new Exercise("T Bar Row", "Back", "Machine");
        Exercise thighAbductor = new Exercise("Thigh Abductor", "Upper Legs", "Machine");
        Exercise thighAdductor = new Exercise("Thigh Adductor", "Upper Legs", "Machine");
        Exercise threeBenchDip = new Exercise("Three Bench Dip", "Triceps", "Bench");
        Exercise torsoRotation = new Exercise("Torso Rotation", "Abs", "Exercise Ball");
        Exercise transverseStepUp = new Exercise("Transverse Step Up", "Upper Legs", "Bench");
        Exercise tricepsPushdownVBar = new Exercise("Triceps Pushdown V Bar", "Triceps", "Machine");
        Exercise twistingHangingKneeRaise = new Exercise("Twisting Hanging Knee Raise", "Abs", "Pullup Bar");
        Exercise twistingLyingCableCrunch = new Exercise("Twisting Lying Cable Crunch", "Abs", "Machine");
        Exercise unilateralRow = new Exercise("Unilateral Row", "Back", "Machine");
        Exercise vBarPullUp = new Exercise("V Bar Pull Up", "Back", "Pullup Bar");
        Exercise weightPlateDeclineCrunch = new Exercise("Weight Plate Decline Crunch", "Abs", "Bench");
        Exercise weightPlateAroundtheWorldDeclineCrunch = new Exercise("Weight Plate Around the World Decline Crunch", "Abs", "Bench");
        Exercise weightPlateHyperextensionsonExerciseBall = new Exercise("Weight Plate Hyperextensions on Exercise Ball", "Back", "Exercise Ball");
        Exercise weightPlateLyingFaceDownNeckResistance = new Exercise("Weight Plate Lying Face Down Neck Resistance", "Shoulders", "Bench");
        Exercise weightPlateLyingFaceUpNeckResistance = new Exercise("Weight Plate Lying Face Up Neck Resistance", "Shoulders", "Bench");
        Exercise weightPlatePulloveronExerciseBall = new Exercise("Weight Plate Pullover on Exercise Ball", "Triceps", "Exercise Ball");
        Exercise weightPlateRussianTwist = new Exercise("Weight Plate Russian Twist", "Abs", "Bench");
        Exercise weightPlateSideBendonExerciseBall = new Exercise("Weight Plate Side Bend on Exercise Ball", "Abs", "Exercise Ball");
        Exercise weightPlateSissySquat = new Exercise("Weight Plate Sissy Squat", "Upper Legs", "Machine");
        Exercise weightPlateSquat = new Exercise("Weight Plate Squat", "Upper Legs", "Bench");
        Exercise weightedBenchDip = new Exercise("Weighted Bench Dip", "Triceps", "Bench");
        Exercise weightedDropPushUp = new Exercise("Weighted Drop Push Up", "Chest", "Bench");
        Exercise weightedExerciseBallWallSquat = new Exercise("Weighted Exercise Ball Wall Squat", "Upper Legs", "Exercise Ball");
        Exercise weightedHangingKneeRaise = new Exercise("Weighted Hanging Knee Raise", "Abs", "Pullup Bar");
        Exercise weightedPullUps = new Exercise("Weighted Pull Ups", "Back", "Pullup Bar");
        Exercise weightedSideTouches= new Exercise("Weighted Side Touches", "Abs", "Bench");
        Exercise weightedThreeBenchDips = new Exercise("Weighted Three Bench Dips", "Triceps", "Bench");
        Exercise weightedTricepDips = new Exercise("Weighted Tricep Dips", "Triceps", "Machine");
        Exercise wideGripLatPulldown = new Exercise("Wide Grip Lat Pulldown", "Back", "Machine");
        Exercise wideGripPulldownBehindTheNeck = new Exercise("Wide Grip Pulldown Behind The Neck", "Back", "Machine");
        Exercise wideGripRearPullUp = new Exercise("Wide Grip Rear Pull-Up", "Back", "Pullup Bar");
        Exercise windshieldWipers = new Exercise("Windshield Wipers", "Abs", "Pullup Bar");



        exerciseRepository.save(bicepCurl);
        exerciseRepository.save(backSquat);
        exerciseRepository.save(deadlift);
        exerciseRepository.save(benchPress);
        exerciseRepository.save(reverseChestFly);
        exerciseRepository.save(barbellJammers);
        exerciseRepository.save(abCrunchMachine);
        exerciseRepository.save(backExtensionMachine);
        exerciseRepository.save(bandBackFlyes);
        exerciseRepository.save(bandWeightedSitUp);
        exerciseRepository.save(bandsSeatedShoulderPress);
        exerciseRepository.save(barbellMilitaryPress);
        exerciseRepository.save(barbellBentArmPullover);
        exerciseRepository.save(barbellBodyRow);
        exerciseRepository.save(barbellBradfordRockyPress);
        exerciseRepository.save(barbellCloseGripBenchPress);
        exerciseRepository.save(barbellCloseGripPreacherCurl);
        exerciseRepository.save(barbellCloseGripPressBehindNeck);
        exerciseRepository.save(barbellCloseGripSeatedConcentrationCurl);
        exerciseRepository.save(barbellCurlsLyingAgainstIncline);
        exerciseRepository.save(barbellDeclineBenchLunge);
        exerciseRepository.save(barbellDeclineBenchPress);
        exerciseRepository.save(barbellDeclineBenchPress);
        exerciseRepository.save(barbellDeclinePullover);
        exerciseRepository.save(barbellFrontRaiseAndPullover);
        exerciseRepository.save(barbellGoodMorningOffPins);
        exerciseRepository.save(barbellHighInvertedRow);
        exerciseRepository.save(barbellHipThrust);
        exerciseRepository.save(barbellInclineBenchPress);
        exerciseRepository.save(barbellInclineBenchPull);
        exerciseRepository.save(barbellInclineBenchRow);
        exerciseRepository.save(barbellJMPress);
        exerciseRepository.save(barbellLyingBackOfTheHeadExtension);
        exerciseRepository.save(barbellLyingCamberedRow);
        exerciseRepository.save(barbellLyingCloseGripTricepsPressToChin);
        exerciseRepository.save(benchDip);
        exerciseRepository.save(benchPressMachine);
        exerciseRepository.save(benchPushup);
        exerciseRepository.save(biceptCurlMachine);
        exerciseRepository.save(butterfly);
        exerciseRepository.save(cableBackInclinePushdown);
        exerciseRepository.save(cableBentOverLowPulleyLateral);
        exerciseRepository.save(cableCalfRaise);
        exerciseRepository.save(cableCloseGripCurl);
        exerciseRepository.save(cableConcentrationCurl);
        exerciseRepository.save(cableCrossOver);
        exerciseRepository.save(cableCrunch);
        exerciseRepository.save(cableDeadlift);
        exerciseRepository.save(cableDeclineChestFly);
        exerciseRepository.save(cableDeclinePress);
        exerciseRepository.save(cableDeclinePullover);
        exerciseRepository.save(cableDragCurl);
        exerciseRepository.save(cableElevatedRows);
        exerciseRepository.save(cableExternalRotation);
        exerciseRepository.save(cableFlatBenchFly);
        exerciseRepository.save(cableFrontRaise);
        exerciseRepository.save(dip);
        exerciseRepository.save(dragonFlag);
        exerciseRepository.save(dumbbellSeatedFrontHammerRaises);
        exerciseRepository.save(dumbbellAlternateBentOverKickback);
        exerciseRepository.save(dumbbellAlternateBentOverReverseFly);
        exerciseRepository.save(dumbbellAlternateBicepCurl);
        exerciseRepository.save(dumbbellAlternateHammerCurl);
        exerciseRepository.save(dumbbellAlternateHammerPreacherCurl);
        exerciseRepository.save(dumbbellAlternateInclineCurl);
        exerciseRepository.save(dumbbellAlternatingDeltoidRaise);
        exerciseRepository.save(dumbbellArnoldPress);
        exerciseRepository.save(dumbbellDeadlift);
        exerciseRepository.save(dumbbellDeclineFly);
        exerciseRepository.save(dumbbellDeclinePress);
        exerciseRepository.save(dumbbellDeclineTricepsExtension);
        exerciseRepository.save(dumbbellDoubleInclineShoulderRaise);
        exerciseRepository.save(dumbbellFly);
        exerciseRepository.save(dumbbellFrontInclineRaise);
        exerciseRepository.save(dumbbellInclineCurl);
        exerciseRepository.save(dumbbellInclineFly);
        exerciseRepository.save(dumbbellLateralRaise);
        exerciseRepository.save(dumbbellLunges);
        exerciseRepository.save(ezBarDeclineCloseGripSkullCrusher);
        exerciseRepository.save(ezBarDeclineTricepsExtension);
        exerciseRepository.save(ezBarFrenchPressOnExerciseBall);
        exerciseRepository.save(ezBarInclineTricepsExtension);
        exerciseRepository.save(ezBarLyingCloseGripBehindTheHeadTricepsExtension);
        exerciseRepository.save(ezBarReverseGripPreacherCurl);
        exerciseRepository.save(ezBarSeatedCloseGripConcentrationCurl);
        exerciseRepository.save(ezBarSeatedReverseGripFrenchPress);
        exerciseRepository.save(ezBarTricepsExtension);
        exerciseRepository.save(flatBenchLegPullIn);
        exerciseRepository.save(flatBenchLyingLegRaise);
        exerciseRepository.save(frontStepUp);
        exerciseRepository.save(fullRangeOfMotionLatPulldown);
        exerciseRepository.save(girondaSternumChinUps);
        exerciseRepository.save(gorillaChinUpWithCrunch);
        exerciseRepository.save(hackCalfRaise);
        exerciseRepository.save(hackSquat);
        exerciseRepository.save(hammerGripPullUp);
        exerciseRepository.save(hangingKneeRaise);
        exerciseRepository.save(hangingLegRaise);
        exerciseRepository.save(hangingPike);
        exerciseRepository.save(hipAdduction);
        exerciseRepository.save(hyperextensionsBackExtensions);
        exerciseRepository.save(isoLateralWidePulldown);
        exerciseRepository.save(jackknifeSitUpOnBench);
        exerciseRepository.save(kneelingLegCurl);
        exerciseRepository.save(legExtensionWithOneLeg);
        exerciseRepository.save(legExtensions);
        exerciseRepository.save(legPress);
        exerciseRepository.save(legPressMachine);
        exerciseRepository.save(legPressWithWideStance);
        exerciseRepository.save(leverageChestPress);
        exerciseRepository.save(leverageDeclineChestPress);
        exerciseRepository.save(leverageInclineChestPress);
        exerciseRepository.save(leverageMachineHighRow);
        exerciseRepository.save(leverageMachineIsoRow);
        exerciseRepository.save(leverageMachineIsoRow);
        exerciseRepository.save(leverageShoulderPress);
        exerciseRepository.save(leverageShrug);
        exerciseRepository.save(lyingCableCrunch);
        exerciseRepository.save(lyingCableKneeRaiseOnBench);
        exerciseRepository.save(lyingLegCurls);
        exerciseRepository.save(lyingLegRaiseWithHipThrustOnBench);
        exerciseRepository.save(lyingMachineSquat);
        exerciseRepository.save(machineAssistedChinUp);
        exerciseRepository.save(machineAssistedDip);
        exerciseRepository.save(machineAssistedHammerGripPullUp);
        exerciseRepository.save(machineAssistedPullUp);
        exerciseRepository.save(machineCurlWithHammerGrip);
        exerciseRepository.save(machineCurlWithReverseGrip);
        exerciseRepository.save(machineDeclineChestPress);
        exerciseRepository.save(machineDeltoidRaise);
        exerciseRepository.save(machineInclineChestPress);
        exerciseRepository.save(machineInnerChestPress);
        exerciseRepository.save(machineLatPullDown);
        exerciseRepository.save(machineReverseFlyes);
        exerciseRepository.save(machineShoulderPress);
        exerciseRepository.save(machineTBarReverseGripRow);
        exerciseRepository.save(machineTricepsExtension);
        exerciseRepository.save(medicineBallBicepsCurlonExerciseBall);
        exerciseRepository.save(mixedGripChinUp);
        exerciseRepository.save(narrowGripLatPullDown);
        exerciseRepository.save(neckPress);
        exerciseRepository.save(obliqueCrunchesWithBench);
        exerciseRepository.save(obliqueRaisesOnParallelBars);
        exerciseRepository.save(onYourBackQuadStretch);
        exerciseRepository.save(oneArmChinUp);
        exerciseRepository.save(oneArmIsoLateralHighRow);
        exerciseRepository.save(oneArmIsoLateralWidePulldown);
        exerciseRepository.save(oneArmedBiasedPushUp);
        exerciseRepository.save(oneHandedHang);
        exerciseRepository.save(oneLeg45DegreeLegPress);
        exerciseRepository.save(oneLegCalfPressOnLegPress);
        exerciseRepository.save(oneLegDonkeyCalfRaise);
        exerciseRepository.save(oneLegHackSquat);
        exerciseRepository.save(oneLegReverseHyperonFlatBench);
        exerciseRepository.save(parallelBarLegRaise);
        exerciseRepository.save(pinPresses);
        exerciseRepository.save(plankOnExerciseBall);
        exerciseRepository.save(plankOnExerciseBall);
        exerciseRepository.save(plankWithFeetOnBench);
        exerciseRepository.save(preacherCurlMachine);
        exerciseRepository.save(pullUps);
        exerciseRepository.save(pushUpwithFeetElevated);
        exerciseRepository.save(pushUpwithFeetOnAnExerciseBall);
        exerciseRepository.save(reverseGripLatPullDown);
        exerciseRepository.save(reverseGripMachineLatPullDown);
        exerciseRepository.save(reverseGripVerticalRow);
        exerciseRepository.save(reverseHackSquat);
        exerciseRepository.save(reverseHyperonFlatBench);
        exerciseRepository.save(reverseLyingTBarMachineRow);
        exerciseRepository.save(rockyPullUpsandPulldowns);
        exerciseRepository.save(rollOveronExerciseBall);
        exerciseRepository.save(romanChairTwistingKneeRaise);
        exerciseRepository.save(seatedCalfRaise);
        exerciseRepository.save(seatedFlatBenchLegPullIn);
        exerciseRepository.save(seatedHamstringStretchonExerciseBall);
        exerciseRepository.save(seatedLegCurl);
        exerciseRepository.save(seatedLegCurlwithOneLeg);
        exerciseRepository.save(seatedLegTucks);
        exerciseRepository.save(seatedMachineRow);
        exerciseRepository.save(seatedOneLegCalfRaise);
        exerciseRepository.save(seatedTricepDip);
        exerciseRepository.save(seatedTwoArmPalmsUpLowPulleyWristCurl);
        exerciseRepository.save(shoulderRaise);
        exerciseRepository.save(shoulderRaiseMachine);
        exerciseRepository.save(sideStepUp);
        exerciseRepository.save(singleBenchDip);
        exerciseRepository.save(singleLegCurl);
        exerciseRepository.save(smithMachineBenchPress);
        exerciseRepository.save(smithMachineBentOverRow);
        exerciseRepository.save(smithMachineBicepCurl);
        exerciseRepository.save(smithMachineCloseGripBenchPress);
        exerciseRepository.save(smithMachineCloseGripShoulderPress);
        exerciseRepository.save(smithMachineDeadlift);
        exerciseRepository.save(smithMachineDeclineBenchPress);
        exerciseRepository.save(smithMachineDeclineCloseGripBenchPress);
        exerciseRepository.save(smithMachineFrankensteinSquat);
        exerciseRepository.save(smithMachineFrontSquat);
        exerciseRepository.save(smithMachineGoodMorning);
        exerciseRepository.save(smithMachineHackSquat);
        exerciseRepository.save(smithMachineInclineBenchPress);
        exerciseRepository.save(smithMachineInclineShoulderRaise);
        exerciseRepository.save(smithMachineInclineTricepExtension);
        exerciseRepository.save(smithMachineLunge);
        exerciseRepository.save(smithMachineOneArmRow);
        exerciseRepository.save(smithMachineOneLegCalfRaise);
        exerciseRepository.save(smithMachineOverheadShoulderPress);
        exerciseRepository.save(smithMachineRearDeltRow);
        exerciseRepository.save(smithMachineReverseCalfRaises);
        exerciseRepository.save(smithMachineReverseCloseGripBenchPress);
        exerciseRepository.save(smithMachineReverseGripBenchPress);
        exerciseRepository.save(smithMachineReverseGripBentOverRow);
        exerciseRepository.save(smithMachineReverseGripInclineBenchPress);
        exerciseRepository.save(smithMachineSeatedOneLegCalfRaise);
        exerciseRepository.save(smithMachineSeatedWristCurl);
        exerciseRepository.save(smithMachineShoulderPress);
        exerciseRepository.save(smithMachineShoulderPressBehindtheNeck);
        exerciseRepository.save(smithMachineShrug);
        exerciseRepository.save(smithMachineSingleLegSplitSquat);
        exerciseRepository.save(smithMachineSquat);
        exerciseRepository.save(smithMachineSquattoBench);
        exerciseRepository.save(smithMachineStandingBehindtheBackWristCurl);
        exerciseRepository.save(smithMachineStiffLeggedDeadlift);
        exerciseRepository.save(smithMachineToeRaise);
        exerciseRepository.save(smithMachineUprightRow);
        exerciseRepository.save(smithMachineWideGripBenchPress);
        exerciseRepository.save(smithMachineWideGripDeclineBenchPress);
        exerciseRepository.save(smithMachineWideGripShoulderPress);
        exerciseRepository.save(smithMachineZercherSquat);
        exerciseRepository.save(spinalStretch);
        exerciseRepository.save(standingCalfRaises);
        exerciseRepository.save(standingElevatedQuadStretch);
        exerciseRepository.save(standingGastrocnemiusCalfStretch);
        exerciseRepository.save(standingStraightLegHamstringContractRelaxonExerciseBall);
        exerciseRepository.save(storkStancewithExerciseBall);
        exerciseRepository.save(supineAbCrunchMachine);
        exerciseRepository.save(supineStraightLegHamstringStretchonExerciseBall);
        exerciseRepository.save(tBarLyingRow);
        exerciseRepository.save(tBarRow);
        exerciseRepository.save(thighAbductor);
        exerciseRepository.save(thighAdductor);
        exerciseRepository.save(threeBenchDip);
        exerciseRepository.save(torsoRotation);
        exerciseRepository.save(transverseStepUp);
        exerciseRepository.save(tricepsPushdownVBar);
        exerciseRepository.save(twistingHangingKneeRaise);
        exerciseRepository.save(twistingLyingCableCrunch);
        exerciseRepository.save(unilateralRow);
        exerciseRepository.save(vBarPullUp);
        exerciseRepository.save(weightPlateDeclineCrunch);
        exerciseRepository.save(weightPlateAroundtheWorldDeclineCrunch);
        exerciseRepository.save(weightPlateHyperextensionsonExerciseBall);
        exerciseRepository.save(weightPlateLyingFaceDownNeckResistance);
        exerciseRepository.save(weightPlateLyingFaceUpNeckResistance);
        exerciseRepository.save(weightPlateAroundtheWorldDeclineCrunch);
        exerciseRepository.save(weightPlateHyperextensionsonExerciseBall);
        exerciseRepository.save(weightPlateLyingFaceDownNeckResistance);
        exerciseRepository.save(weightPlateLyingFaceUpNeckResistance);
        exerciseRepository.save(weightPlatePulloveronExerciseBall);
        exerciseRepository.save(weightPlateRussianTwist);
        exerciseRepository.save(weightPlateSideBendonExerciseBall);
        exerciseRepository.save(weightPlateSissySquat);
        exerciseRepository.save(weightPlateSquat);
        exerciseRepository.save(weightedBenchDip);
        exerciseRepository.save(weightedDropPushUp);
        exerciseRepository.save(weightedExerciseBallWallSquat);
        exerciseRepository.save(weightedHangingKneeRaise);
        exerciseRepository.save(weightedPullUps);
        exerciseRepository.save(weightedSideTouches);
        exerciseRepository.save(weightedThreeBenchDips);
        exerciseRepository.save(weightedTricepDips);
        exerciseRepository.save(weightedThreeBenchDips);
        exerciseRepository.save(weightedTricepDips);
        exerciseRepository.save(wideGripLatPulldown);
        exerciseRepository.save(wideGripPulldownBehindTheNeck);
        exerciseRepository.save(wideGripRearPullUp);
        exerciseRepository.save(windshieldWipers);


        ArrayList<ExercisePlanExercise> exercisesSetsReps = new ArrayList<>();
        exercisesSetsReps.add(new ExercisePlanExercise(5, 25, 25, false, bicepCurl));
        ExercisePlan exercisePlan = new ExercisePlan("Big body", exercisesSetsReps, user);
        exercisePlanRepository.save(exercisePlan);

        return args -> {
            log.info("Preloading " + foods);
            log.info("Preloading " + apple);
            log.info("Preloading " + breakfast);
            log.info("Preloading " + user);
            log.info("Preloading " + bicepCurl);
            log.info("Preloading " + exercisePlan);
            log.info("Preloading " + userRepository.save(new User("doe","doe@gmail.com","doepassword")));
        };
    }
}
